[project]
name = "book-recommendation-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logfire>=4.22.0",
    "openai-agents>=0.8.4",
    "pydantic-ai-slim[openrouter]>=1.58.0",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
